apiVersion: v1
imagePullSecrets:
- name: drydockcreds
kind: ServiceAccount
metadata:
  labels:
    category: rbac
    deploy: sourcegraph
    sourcegraph-resource-requires: no-cluster-admin
    app.kubernetes.io/component: grafana
  name: grafana
